name       : python-typeguard
version    : 2.10.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/t/typeguard/typeguard-2.10.0.tar.gz : d830132dcd544d3f8a2a842ea739eaa0d7c099fcebb9dcdf3802f4c9929d8191
homepage   : https://github.com/agronholm/typeguard
license    : MIT
component  : programming.python
summary    : Run-time type checker for Python
description: |
    This library provides run-time type checking for functions defined with PEP 484 argument (and return) type annotations.
builddeps  :
    - python-pytest
    - python-setuptools-scm
    - python-typing-extensions
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-version-tag.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
