name       : python-typeguard
version    : 2.9.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/bd/5e/bcf5dd82607a2e77d4e81da33223bafcee3a1011445173b5bf48af247167/typeguard-2.9.1.tar.gz : 529ef3d88189cc457f4340388028412f71be8091c2c943465146d4170fb67288
homepage   : https://github.com/agronholm/typeguard
license    : MIT
component  : programming.python
summary    : Run-time type checker for Python
description: |
    This library provides run-time type checking for functions defined with PEP 484 argument (and return) type annotations.
builddeps  :
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
