name       : python-typeguard
version    : 4.0.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/t/typeguard/typeguard-4.0.0.tar.gz : 194fb3dbcb06ea9caf7088f3befee014de57961689f9c859ac5239b1ef61d987
homepage   : https://github.com/agronholm/typeguard
license    : MIT
component  : programming.python
summary    : Run-time type checker for Python
description: |
    This library provides run-time type checking for functions defined with PEP 484 argument (and return) type annotations.
builddeps  :
    - python-build
    - python-installer
    - python-mypy           # check
    - python-pytest         # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v 
