name       : python-typeguard
version    : 2.13.3
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/t/typeguard/typeguard-2.13.3.tar.gz : 00edaa8da3a133674796cf5ea87d9f4b4c367d77476e185e80251cc13dfbb8c4
homepage   : https://github.com/agronholm/typeguard
license    : MIT
component  : programming.python
summary    : Run-time type checker for Python
description: |
    This library provides run-time type checking for functions defined with PEP 484 argument (and return) type annotations.
builddeps  :
    - python-pytest
    - python-setuptools-scm
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not mypy'
